CC = cl
CFLAGS = /nologo /Zi /O2 /MD /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /I../src /I../pixman/src /I../boilerplate
LDFLAGS = ../src/cairo.lib ../pixman/src/pixman.lib ../boilerplate/boiler.lib libpng.lib zlib.lib gdi32.lib msimg32.lib user32.lib

TESTS = 			\
a8-mask				\
caps-joins			\
caps-joins-alpha		\
caps-sub-paths			\
clip-all			\
clip-fill-rule			\
clip-fill-rule-pixel-aligned	\
clip-nesting			\
clip-operator			\
clip-twice			\
composite-integer-translate-source \
composite-integer-translate-over \
composite-integer-translate-over-repeat \
create-for-stream		\
create-from-png			\
create-from-png-stream		\
dash-caps-joins			\
dash-no-dash			\
dash-offset-negative		\
dash-scale			\
dash-zero-length		\
degenerate-path			\
device-offset			\
device-offset-positive		\
extend-reflect			\
fill-and-stroke			\
fill-and-stroke-alpha		\
fill-and-stroke-alpha-add	\
fill-rule			\
filter-nearest-offset		\
font-face-get-type		\
font-matrix-translation		\
glyph-cache-pressure		\
get-and-set			\
get-clip			\
get-group-target		\
get-path-extents		\
gradient-alpha			\
leaky-dash			\
leaky-polygon			\
line-width			\
line-width-scale		\
linear-gradient			\
mask				\
mask-ctm			\
mask-surface-ctm		\
move-to-show-surface		\
new-sub-path			\
nil-surface			\
operator-clear			\
operator-source			\
paint				\
paint-source-alpha		\
paint-with-alpha		\
pattern-get-type		\
pattern-getters			\
pixman-rotate			\
rectangle-rounding-error	\
scale-source-surface-paint	\
select-font-face		\
select-font-no-show-text	\
self-copy			\
self-intersecting		\
set-source			\
show-text-current-point		\
source-clip			\
source-surface-scale-paint	\
surface-finish-twice		\
surface-pattern			\
text-antialias-gray		\
text-antialias-none		\
text-antialias-subpixel		\
text-cache-crash		\
text-pattern			\
text-rotate			\
transforms			\
translate-show-surface		\
trap-clip			\
unantialiased-shapes		\
unbounded-operator		\
user-data			\
rel-path                        \
push-group			\
zero-alpha			\
$(NULL)

TESTCORE_SOURCES = \
	cairo-test.c \
	buffer-diff.c \
	$(NULL)

TEST_EXE = $(addsuffix .exe,$(TESTS))

all: $(TEST_EXE)

%.exe: %.c
	@$(CC) $(CFLAGS) /Fe"$@" $<  $(TESTCORE_SOURCES) /link $(LDFLAGS)

test: $(TEST_EXE)
	@for exe in $(TEST_EXE) ; do \
		echo $$exe ; \
		( ./$$exe || exit 0 ) ; \
	done

html:
	@echo Creating index.html...
	@perl make-html.pl > index.html
