top_srcdir = ..
include $(top_srcdir)/build/Makefile.win32.common
include $(top_srcdir)/test/Makefile.sources

CFLAGS += -I../src -I../boilerplate -I./pdiff

TEST_LIBS = ./pdiff/pdiff.lib $(top_srcdir)/src/$(CFG)/cairo-static.lib $(top_srcdir)/boilerplate/$(CFG)/boiler.lib

all: inform cairo-test-suite.exe

cairo-test-constructors.c: Makefile.sources Makefile.win32 $(test_sources) make-cairo-test-constructors.sh
	sh ./make-cairo-test-constructors.sh $(test_sources) > $@

SOURCES = $(cairo_test_suite_sources) $(test_sources) cairo-test-constructors.c

OBJECTS = $(patsubst %.c, $(CFG)/%-static.obj, $(SOURCES))

cairo-test-suite.exe: $(OBJECTS) $(TEST_LIBS)
	$(CC) $(OPT) $(MS_MDFLAGS) $(OBJECTS) -Fe"$@" -link $(LDFLAGS) $(TEST_LIBS) $(CAIRO_LIBS)

./pdiff/pdiff.lib:
	(cd pdiff ; $(MAKE) -f Makefile.win32)

$(top_srcdir)/src/$(CFG)/cairo-static.lib:
	$(MAKE) -C $(top_srcdir)/src -f Makefile.win32

$(top_srcdir)/boilerplate/$(CFG)/boiler.lib:
	$(MAKE) -C $(top_srcdir)/boilerplate -f Makefile.win32

.PHONY: check test

check: inform cairo-test-suite.exe
	./cairo-test-suite.exe

test: inform check
