top_srcdir = ..
include $(top_srcdir)/build/Makefile.win32.common
include Makefile.win32.features

CFLAGS += -I../src

HEADERS = \
	$(enabled_cairo_boilerplate_headers) \
	$(enabled_cairo_boilerplate_private) \
	$(NULL)

SOURCES = \
	$(enabled_cairo_boilerplate_sources) \
	cairo-boilerplate-constructors.c \
	$(NULL)

OBJECTS = $(patsubst %.c, $(CFG)/%-static.obj, $(SOURCES))

cairo-boilerplate-constructors.c: Makefile.sources Makefile.win32 $(enabled_cairo_boilerplate_sources) make-cairo-boilerplate-constructors.sh
	sh ./make-cairo-boilerplate-constructors.sh $(enabled_cairo_boilerplate_sources) > $@

all: $(CFG)/boiler.lib


$(CFG)/boiler.lib: $(OBJECTS)
	lib -NOLOGO -OUT:$@ $(OBJECTS) $(WIN_LIBS)
